/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LauncherSetupRouteImport } from './routes/launcher-setup'
import { Route as LauncherLoginRouteImport } from './routes/launcher-login'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentHubRouteImport } from './routes/agent/hub'
import { Route as AgentConfigureRouteImport } from './routes/agent/configure'

const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSetupRoute = LauncherSetupRouteImport.update({
  id: '/launcher-setup',
  path: '/launcher-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherLoginRoute = LauncherLoginRouteImport.update({
  id: '/launcher-login',
  path: '/launcher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AgentRoute,
} as any)
const AgentConfigureRoute = AgentConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/scheduler': typeof SchedulerRoute
  '/agent/configure': typeof AgentConfigureRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/scheduler': typeof SchedulerRoute
  '/agent/configure': typeof AgentConfigureRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/scheduler': typeof SchedulerRoute
  '/agent/configure': typeof AgentConfigureRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/activity'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/models'
    | '/scheduler'
    | '/agent/configure'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/activity'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/models'
    | '/scheduler'
    | '/agent/configure'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/activity'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/models'
    | '/scheduler'
    | '/agent/configure'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  LauncherLoginRoute: typeof LauncherLoginRoute
  LauncherSetupRoute: typeof LauncherSetupRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  SchedulerRoute: typeof SchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-setup': {
      id: '/launcher-setup'
      path: '/launcher-setup'
      fullPath: '/launcher-setup'
      preLoaderRoute: typeof LauncherSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-login': {
      id: '/launcher-login'
      path: '/launcher-login'
      fullPath: '/launcher-login'
      preLoaderRoute: typeof LauncherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/hub': {
      id: '/agent/hub'
      path: '/hub'
      fullPath: '/agent/hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/configure': {
      id: '/agent/configure'
      path: '/configure'
      fullPath: '/agent/configure'
      preLoaderRoute: typeof AgentConfigureRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentConfigureRoute: typeof AgentConfigureRoute
  AgentHubRoute: typeof AgentHubRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentConfigureRoute: AgentConfigureRoute,
  AgentHubRoute: AgentHubRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  LauncherLoginRoute: LauncherLoginRoute,
  LauncherSetupRoute: LauncherSetupRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  SchedulerRoute: SchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
